spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: 1.0

accounts:
  message: "Welcome to My Bank Accounts related prod APIs"
  contactDetails:
    name: "Arunprem"
    email: "{cipher}64398b1ba60a8117820fc5b4985002aa5ba49ce27845992e3a02ee9f6210cac6371c91e0656e9be3463c7920de9d48b5"
  onCallSupport:
    -9495205259
