server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # Optional: You can set this according to your schema management strategy.
    sql:
      init:
        mode: always
  config:
    import:
      - "cards-qa.yml"
      - "cards-prod.yml"
  profiles:
    active:
      - "qa"

build:
  version: 3.0

cards:
  message: "Welcome to My Bank Cards related local APIs"
  contactDetails:
    name: "Arunprem"
    email: "arun.612675@kerala.gov.in"
  onCallSupport:
    - "9495205259"
    - "1234567890"
