spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: 2.0

cards:
  message: "Welcome to My Bank Cards related qa APIs"
  contactDetails:
    name: "Arunp"
    email: "arun.612675@kerala.gov.in"
  onCallSupport:
    - "9495205259"
    - "1234567890"
