server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # Optional: You can set this according to your schema management strategy.
    sql:
      init:
        mode: always
  config:
    import:
      - "loans-qa.yml"
      - "loans-prod.yml"
  profiles:
    active: "qa"

build:
  version: 3.0

loans:
  message: "Welcome to My Bank Loans related local APIs"
  contactDetails:
    name: "Arunprem"
    email: "arun.612675@kerala.gov.in"
  onCallSupport:
    - "9495205259"
    - "1234567890"
